# Generated by Django 3.1.3 on 2021-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210109_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='article_content',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='article_content1',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='article_content2',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='article_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='article_title1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='article_title2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='concept',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='post',
            name='sno',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
