# Generated by Django 3.1.3 on 2021-01-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210110_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
